version: '3.1'

# secrets:
#   db_uri:
#     file: run/secrets/db_uri.txt

services:
  server:
    restart: always
    build: server/
    command: node app.js
    ports:
      - '80:3001'
    # secrets:
    #   - db_uri
  client:
    build: client/
    command: npm start
    network_mode: host
    depends_on:
      - server